```yaml
name: secrets

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: check whether the secret is available
        env:
          API_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        run: |
          if [ -z "$API_KEY" ]; then
            echo "Secret AWS_ACCESS_KEY is not there. Check the GitHub Secrets."
          fi

          echo "Secret is available. Length is ${#API_KEY} characters."

      - name: check whether variable is there in the GitHub
        env:
          VAR_KEY: ${{ vars.AWS_VAR_KEY }}
        run: |
          if [ -z "$VAR_KEY" ]; then
            echo "Variable is not there in the GitHub."
          fi

          echo "Variable is there and the length is ${#VAR_KEY}."
```
